### ISSUE TITLE
Rule context should be cleared on every re-execution of a rule

### ISSUE THREAD

**Issue by kaikreuzer** [marinmitev/smarthome#118]
Currently, the rule context map is kept filled across the executions of the rule.

This can cause problems, because modules cannot know whether information is from the current execution or from previous ones.

Imagine two triggers T1 and T2, which trigger if Item A updates to ON, resp. Item B updates to ON.

If you know have:
A updates to ON -> T1 triggers, context is filled with A->ON
A updates to OFF -> No triggers, since nobody reacts on OFF
B updates to ON -> T2 triggers, context now contains A->ON, B->ON.

There are actually two problems:
1. A following module cannot determine which trigger has been triggered as both A and B are in the context.
2. The module might imply that A is ON, but this is a false assumption.

**Comment by danchom** [comment]
Yes there are sensors which sends only ON signal and never OFF, and in this case this scenario is relevant. But  on the other case if we want to execute a rule when A and B are ON:
A updates to ON -> T1 triggers, context is filled with A->ON
A && B is OFF because context contains only A->ON
B updates to ON -> T2 triggers, context is filled with B->ON
A && B is OFF because context contains only B->ON
and therefor A && B will never succeed.
We are going to set a system property wihch will define rule engine behaviour. Unfortunately this behaviour will be applied to all triggers in all rule. May be it is better to have a triggers property which defines behaviour of concrete trigger?

**Comment by kaikreuzer** [comment]
Adding a system property to allow an invalid behavior of the rule engine is imho not an option.

As discussed, you are completely mixing up events and states here.
You mistake the information A->ON as a state, while it is only an information about an event. If an event has occurred in the past (as in my example), it is simply WRONG to assume that this is identical to the current state.
For your use case, you will need access to the current state of your entities, i.e. you need to be able to access A.state (e.g. by giving the handler access to the ItemRegistry)

**Comment by danchom** [comment]
I'm not sure about that. You can't always get state of the Item or the state is not correct at the moment of getting. For example if A & B are motion detectors in different rooms and the rule has to be executed when the motions are detected in both places. The triggered data comes consequently and therefor A & B will never be satisfied.

**Comment by kaikreuzer** [comment]
> A & B will never be satisfied.

Correct, because two events will never ever happen at the very same time. This is why we said that the events are combined as a logical OR, i.e. only one of them is active and triggers the execution flow.

**Comment by danchom** [comment]
Yes, but how do you solve the problem when we want to execute a rule only when on both places there are  motion

**Comment by kaikreuzer** [comment]
By checking if A.state==ON, if we get the trigger event from B and vice versa.

**Comment by danchom** [comment]
I've removed system property and updated PR #123
