### ISSUE TITLE
RuleRegistry is missing isEnabled method

### ISSUE THREAD

**Issue by kaikreuzer** [marinmitev/smarthome#185]
It must be possible to retrieve the enabled status for a rule from the registry. It therefore should have a method

```
Boolean isEnabled(String uid)
```

which either returns true, false or null (if rule does not exist).

**Comment by danchom** [comment]
It will be added:
    /**
     \* This method gets enable status for a rule.
     *
     \* @param ruleUID uid of rule
     \* @return true when the rule is enabled, false when it is disabled or not available.
     */
    public boolean isEnabled(String ruleUID);

I think it is better to return boolean rather then Boolean object, because it should be symmetric  to the method:

public void setEnabled(String uid, boolean isEnabled);

**Comment by danchom** [comment]
Done in PR #191

**Comment by BenediktNiehues** [comment]
As Kai requested to return null explicitly if the rule does not exist, we should wait for his feedback before we close this issue.

**Comment by kaikreuzer** [comment]
Providing an answer (false) to a question that has no answer (because the rule in question does not exist) does not make sense to me. The symmetricity is provided by Java through auto-boxing, so this is not really an argument for me. If you really want to stick to boolean, I think we would then need a RuleNotFound exception that would be thrown otherwise. I personally rather like null return values over catched exceptions.

**Comment by danchom** [comment]
The answer depends of point of view to the question. If you want to know if a rule is enabled then the true is an answer that it exists and it is in enable state. Otherwise when the rule is missing or it is disabled it can't return true to the isEnable question. 
If we have three return options (true, false, null) we are answering to two questions at the same time:
1) if the rule exists
2) if the rule is enabled.
but the question was only if it can run. 
Wheather it is enabled can be check by the get() call
Imho type of set object should be same as the type of get object. I agree that throwing an exception is not good variant.
If you prefer to have a null result for not existing rules I'll change the implementation.

**Comment by BenediktNiehues** [comment]
For me the existence of a rule, is a second pair of shoes as well. I am fine with returning true if a rule is enabled and false if a rule is not enabled or does not exist because a not existing rule can not be enabled. I don't think that an exception is needed if the rule does not exist. @kaikreuzer do you have a use case where it could be more common to have null returned if the rule does not exist?

**Comment by danchom** [comment]
Btw there is a bug in implementation, I'll fix it when you decide for return value.

**Comment by kaikreuzer** [comment]
Well, think of accessing this method through a rest call (/rules/xyz/isEnabled). As a caller, you would clearly expect a 404 and not a "false" as a response. And I think this API style also makes sense on the Java API.

Btw, as we defined that a rule is by default enabled unless it is manually disabled, wouldn't the correct answer be "true" for a non-existing rule? Maybe this shows that it is a dangerous terrain to do such implicit assumptions.

**Comment by danchom** [comment]
I understand the rest issue it is better to create one instead of two calls.
Imho something must exist before it can run. 
The question is what answer we receive to the call of isEnabled method:
1)  is this rule is running ? (then it should be enabled and available)
2) is this rule has enabled state

btw if the rule is dissabled and missing (it was disabled and removed) what should the method return null or false ?
I think it should return false. The last persisted state of this rule

**Comment by BenediktNiehues** [comment]
Final solution is: 
- false if rule exists and is not enabled
- true if rule exists and is enabled
- null if rule does not exist
