### ISSUE TITLE
Swagger UI bundle for ESH that reads the swagger annotations from the REST resources

### ISSUE THREAD

**Issue by kaikreuzer** [marinmitev/smarthome#235]
With https://github.com/eclipse/smarthome/pull/510/files, we have added Swagger annotations to all ESH REST resources.
What is missing though, is an optional bundle that can be deployed on a runtime, which reads these annotations and provides the Swagger UI.
There is something similar in place for openHAB 2 at https://github.com/openhab/openhab2/tree/master/bundles/io/org.openhab.io.rest.docs, but this solution only reads JAX-RS annotations, but not the Swagger ones.

**Comment by hristostanchev** [comment]
Kai I remember that you ask me if we support Swagger 2.0 spec, if we can generate standalone version of Swagger doc and if solve some of the problems with swagger annotations ? Is this all or something else was needed ? I talk to Elena and she will comment here. We can also donate what we did even it is not perfect.

**Comment by kaikreuzer** [comment]
>  Is this all or something else was needed ? 

Besides the static documentation, there should also be a servlet in an optional bundle that provides the swagger ui at runtime, similar to what exists at openHAB 2: http://demo.openhab.org:9080/doc/index.html

**Comment by egramatova** [comment]
Hi,
In order to generate REST API documentation based on swagger 2.0 specification we have integrated swagger-doclet-1.1.0 with several modifications/bug fixes that have been described in this issue - https://github.com/teamcarma/swagger-jaxrs-doclet/issues/106. The doclet is called during the build process of bundles that provide REST APIs - generated REST API documentation artifacts are packed in OSGI-INF/rest/apidocs bundle entry and X-ProSyst-Restdoc-Included manifest header is added for all bundles that provide REST API documentation resources.

For browsing REST API documentation and exploring the existing REST web services available in the OSGi runtime we have integrated swagger-ui-2.1.1 - all swagger web resources and registered with the OSGi HTTP service along with a servlet that handles the requests. We have implemented several modifications/improvements in the swagger web resources - ProSyst branding is added, basic authorization is used for performing REST calls, navigational panel is added in order to hierarchically organize the available REST APIs and ease the browsing through the APIs.

We have implemented a mechanism for discovery of swagger REST API documentation resources that have been packed in bundles marked with the X-ProSyst-Restdoc-Included manifest header. Additionally, a mechanism for dynamic discovery and loading of REST API documentation via OSGi services is  supported. The mechanism is based on the white board pattern. Bundles that wish to dynamically generate and provide REST API documentation may do so by registering an OSGi service which provides REST API documentation artifacts in form of JSON objects based on the swagger specification. We have also added a utility to ease building of the JSON objects.

**Comment by hristostanchev** [comment]
We are using jax-rs, jaxb and swagger annotations from what we talk with Elena. Elena can you comment for what jaxb annotation are needed related to swagger ? 

Kai is OK ProSyst to make initial contribution in ESH for swagger. We need to change the manifest attribute and the branding. I will talk to Elena and her team if they can do this. 

Elena if you can put here also our result from checking if Jersey can work on Compact 2.

**Comment by hristostanchev** [comment]
Swagger can work without jaxb annotations but we need need to check how generated content will look without them. It seems that if there are jaxb annotations swagger is using them. 

We are not yet ready with Jersey check on Compact 2.

**Comment by kaikreuzer** [comment]
As discussed, I have created an ESH issue for further follow-up discussions: https://bugs.eclipse.org/bugs/show_bug.cgi?id=482451
The contribution should then made directly to ESH, not to this automation component PR.
