### ISSUE TITLE
Add context for timer trigger (TimerTriggerTypeDefinition.json)

### ISSUE THREAD

**Issue by smhgit** [marinmitev/smarthome#253]
I think that context should be add to the cronExpression in the config description (TimerTriggerTypeDefinition).

E.g., "context":"cron"

**Comment by kaikreuzer** [comment]
We currently have very limited options defined for the context of config descriptions. They should in general make sense for UIs so that they know how to render it.
I doubt that cron expressions are a good format for any UI to come up with a specific rendering.
I'd rather think we will need composite modules for specific use cases, which then come with a more finegrained configuration, such as an alarm trigger with an hour and a minute parameter etc.
