### ISSUE TITLE
Update MANIFEST.MFs

### ISSUE THREAD

**Issue by kaikreuzer** [marinmitev/smarthome#31]
Set the Execution Environment to OSGi minimal 1.2 for all automation bundles.
Keep compiler settings of IDE/Tycho at 1.7 as is.

**Comment by danchom** [comment]
It is not finish because the maven build fails.
I have reverted manifest to the previous version.
A research has to be made, why the maven build fails when the requirement to the OSGi minimal 1.2 is set

**Comment by marinmitev** [comment]
it is not possible to put both Execution Environment for OSGi minimum1.2 and Java7

**Comment by dnobel** [comment]
So we have to discuss what should be set for automation bundles: Java7 or Java5.

**Comment by kaikreuzer** [comment]
What I said in the issue is "Set the Execution Environment to OSGi minimal 1.2 for all automation bundles.". Nobody asked for putting both Execution Environments for OSGi minimum1.2 and Java7.

**Comment by dnobel** [comment]
I think in the Manifest only OSGi minimal 1.2 has been set. There was a problem with the maven build and the target platform. Some javax problems. ProSyst will provide more details.

**Comment by danchom** [comment]
When we set the manifest header: Bundle-RequiredExecutionEnvironment: OSGi/Minimum-1.2
the following error appears: 
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: com.eclipsesource.jaxrs.jersey.runtime.feature.feature.group 2.17.0.201506221200
[ERROR]   Missing requirement: com.eclipsesource.jaxrs.jersey-min 2.18.0 requires 'package javax.naming 0.0.0' but it could not be found
[ERROR]   Cannot satisfy dependency: com.eclipsesource.jaxrs.jersey.runtime.feature.feature.group 2.17.0.201506221200 depends on: com.eclipsesource.jaxrs.jersey-min [2.18.0]
[ERROR]
[ERROR] Internal error: java.lang.RuntimeException: Failed to resolve target definition C:\Users\danchom.m2\repository\org\eclipse\smarthome\targetplatform\0.8.0-SNAPSHOT\targetplatform-0.8.0-SNAPSHOT-smarthome.target: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from com.eclipsesource.jaxrs.consumer 5.0.0.201506221200 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from com.eclipsesource.jaxrs.jersey-all 2.18.0 to package javax.crypto 0.0.0.; Unable to satisfy dependency from com.eclipsesource.jaxrs.jersey-all 2.18.0 to package javax.crypto.spec 0.0.0.; Unable to satisfy dependency from com.eclipsesource.jaxrs.jersey-all 2.18.0 to package javax.imageio 0.0.0.; Unable to satisfy dependency from com.eclipsesource.jaxrs.jersey-all 2.18
.0 to package javax.imageio.spi 0.0.0.; Unable to satisfy dependency from com.eclipsesource.jaxrs.jersey-all 2.18.0 to package javax.imageio.stream 0.0.0.; Unable to satisfy dependency from com.eclipsesource.jaxrs.jersey-all 2.18.0 to package javax.naming 0.0.0.; Unable to satisfy dependency from com.eclipsesource.jaxrs.jersey-all 2.18.0 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from com.eclipsesource.jaxrs.jersey-min 2.18.0 to package javax.imageio 0.0.0.; Unable to satisfy dependency from com.eclipsesource.jaxrs.jersey-min 2.18.0 to package javax.imageio.spi 0.0.0.; Unable to satisfy dependency from com.eclipsesource.jaxrs.jersey-min 2.18.0 to package javax.imageio.stream 0.0.0.; Unable to satisfy dependency from com.eclipsesource.jaxrs.jersey-min 2.18.0 to package ja
vax.naming 0.0.0.; Unable to satisfy dependency from com.eclipsesource.jaxrs.jersey-min 2.18.0 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from com.jcraft.jsch 0.1.50.v201403120620 to package javax.crypto 0.0.0.; Unable to satisfy dependency from com.jcraft.jsch 0.1.50.v201403120620 to package javax.crypto.interfaces 0.0.0.; Unable to satisfy dependency from com.jcraft.jsch 0.1.50.v201403120620 to package javax.crypto.spec 0.0.0.; Unable to satisfy dependency from com.jcraft.jsch 0.1.50.v201403120620 to package org.ietf.jgss 0.0.0.; Unable to satisfy dependency from com.jcraft.jsch 0.1.51.v201410302000 to package javax.crypto 0.0.0.; Unable to satisfy dependency from com.jcraft.jsch 0.1.51.v201410302000 to package javax.crypto.interfaces 0.0.0.; Unable to satisfy dependen
cy from com.jcraft.jsch 0.1.51.v201410302000 to package javax.crypto.spec 0.0.0.; Unable to satisfy dependency from com.jcraft.jsch 0.1.51.v201410302000 to package org.ietf.jgss 0.0.0.; Unable to satisfy dependency from javax.activation 1.1.0.v201108011116 to package javax.imageio 0.0.0.; Unable to satisfy dependency from javax.activation 1.1.0.v201108011116 to package javax.imageio.metadata 0.0.0.; Unable to satisfy dependency from javax.activation 1.1.0.v201211130549 to package javax.imageio 0.0.0.; Unable to satisfy dependency from javax.activation 1.1.0.v201211130549 to package javax.imageio.metadata 0.0.0.; Unable to satisfy dependency from javax.persistence 1.0.0.v200905011740 to package javax.sql 0.0.0.; Unable to satisfy dependency from org.apache.commons.net 3.2.0.v201305141515 to
 package javax.crypto 0.0.0.; Unable to satisfy dependency from org.apache.commons.net 3.2.0.v201305141515 to package javax.crypto.spec 0.0.0.; Unable to satisfy dependency from org.apache.commons.net 3.2.0.v201305141515 to package javax.net 0.0.0.; Unable to satisfy dependency from org.apache.commons.net 3.2.0.v201305141515 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.1.0.v201103311320 to package javax.crypto 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.1.0.v201103311320 to package javax.crypto.spec 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.1.0.v201103311320 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpc
lient 4.1.0.v201103311320 to package org.ietf.jgss 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.1.2.v201203221030 to package javax.crypto 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.1.2.v201203221030 to package javax.crypto.spec 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.1.2.v201203221030 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.1.2.v201203221030 to package org.ietf.jgss 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.1.3.v201209201135 to package javax.crypto 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.1.3.v201209201135 to package javax.crypto.spec
 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.1.3.v201209201135 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.1.3.v201209201135 to package org.ietf.jgss 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.2.5.v201305222326 to package javax.crypto 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.2.5.v201305222326 to package javax.crypto.spec 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.2.5.v201305222326 to package javax.net 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.2.5.v201305222326 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from org.apache.htt
pcomponents.httpclient 4.2.5.v201305222326 to package org.ietf.jgss 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.2.6.v201311072007 to package javax.crypto 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.2.6.v201311072007 to package javax.crypto.spec 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.2.6.v201311072007 to package javax.net 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.2.6.v201311072007 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.2.6.v201311072007 to package org.ietf.jgss 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.3.6.v201411290715 to package jav
ax.crypto 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.3.6.v201411290715 to package javax.crypto.spec 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.3.6.v201411290715 to package javax.net 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.3.6.v201411290715 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpclient 4.3.6.v201411290715 to package org.ietf.jgss 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpcore 4.2.4.v201310231540 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpcore 4.2.5.v201311072007 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from org.apac
he.httpcomponents.httpcore 4.3.3.v201411290715 to package javax.net 0.0.0.; Unable to satisfy dependency from org.apache.httpcomponents.httpcore 4.3.3.v201411290715 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from org.apache.mina.core 2.0.2.v201108120515 to package javax.crypto 0.0.0.; Unable to satisfy dependency from org.apache.mina.core 2.0.2.v201108120515 to package javax.crypto.spec 0.0.0.; Unable to satisfy dependency from org.apache.mina.core 2.0.2.v201108120515 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from org.apache.mina.core 2.0.2.v201108120515 to package javax.security.sasl 0.0.0.; Unable to satisfy dependency from org.apache.mina.core 2.0.2.v201108120515 to package org.ietf.jgss 0.0.0.; Unable to satisfy dependency from org.apache.mina.cor
e 2.0.7.v201401071602 to package javax.crypto 0.0.0.; Unable to satisfy dependency from org.apache.mina.core 2.0.7.v201401071602 to package javax.crypto.spec 0.0.0.; Unable to satisfy dependency from org.apache.mina.core 2.0.7.v201401071602 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from org.apache.mina.core 2.0.7.v201401071602 to package javax.security.sasl 0.0.0.; Unable to satisfy dependency from org.apache.mina.core 2.0.7.v201401071602 to package org.ietf.jgss 0.0.0.; Unable to satisfy dependency from org.apache.sshd.core 0.5.0.v201108120515 to package javax.crypto 0.0.0.; Unable to satisfy dependency from org.apache.sshd.core 0.5.0.v201108120515 to package javax.crypto.interfaces 0.0.0.; Unable to satisfy dependency from org.apache.sshd.core 0.5.0.v201108120515 to p
ackage javax.crypto.spec 0.0.0.; Unable to satisfy dependency from org.apache.sshd.core 0.5.0.v201108120515 to package javax.security.auth 0.0.0.; Unable to satisfy dependency from org.apache.sshd.core 0.5.0.v201108120515 to package javax.security.auth.callback 0.0.0.; Unable to satisfy dependency from org.apache.sshd.core 0.5.0.v201108120515 to package javax.security.auth.login 0.0.0.; Unable to satisfy dependency from org.apache.sshd.core 0.7.0.v201303101611 to package javax.crypto 0.0.0.; Unable to satisfy dependency from org.apache.sshd.core 0.7.0.v201303101611 to package javax.crypto.interfaces 0.0.0.; Unable to satisfy dependency from org.apache.sshd.core 0.7.0.v201303101611 to package javax.crypto.spec 0.0.0.; Unable to satisfy dependency from org.apache.sshd.core 0.7.0.v20130310161
1 to package javax.security.auth 0.0.0.; Unable to satisfy dependency from org.apache.sshd.core 0.7.0.v201303101611 to package javax.security.auth.callback 0.0.0.; Unable to satisfy dependency from org.apache.sshd.core 0.7.0.v201303101611 to package javax.security.auth.login 0.0.0.; Unable to satisfy dependency from org.apache.sshd.core 0.7.0.v201303101611 to package org.ietf.jgss 0.0.0.; Unable to satisfy dependency from org.eclipse.ecf.provider.filetransfer.ssl 1.0.0.v20140528-1625 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from org.eclipse.ecf.provider.filetransfer.ssl 1.0.0.v20140827-1444 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from org.eclipse.ecf.provider.filetransfer.ssl 1.0.0.v20141221-2352 to package javax.net.ssl 0.0.0.; Unable to satisfy
dependency from org.eclipse.ecf.ssl 1.1.0.v20140528-1625 to package javax.net 0.0.0.; Unable to satisfy dependency from org.eclipse.ecf.ssl 1.1.0.v20140528-1625 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from org.eclipse.ecf.ssl 1.1.0.v20140827-1444 to package javax.net 0.0.0.; Unable to satisfy dependency from org.eclipse.ecf.ssl 1.1.0.v20140827-1444 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from org.eclipse.ecf.ssl 1.1.0.v20141221-2352 to package javax.net 0.0.0.; Unable to satisfy dependency from org.eclipse.ecf.ssl 1.1.0.v20141221-2352 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from org.eclipse.emf.ecore 2.10.0.v20140514-1158 to package javax.crypto 0.0.0.; Unable to satisfy dependency from org.eclipse.emf.ecore 2.10.0.v20140514
-1158 to package javax.crypto.spec 0.0.0.; Unable to satisfy dependency from org.eclipse.emf.ecore 2.10.1.v20140901-1043 to package javax.crypto 0.0.0.; Unable to satisfy dependency from org.eclipse.emf.ecore 2.10.1.v20140901-1043 to package javax.crypto.spec 0.0.0.; Unable to satisfy dependency from org.eclipse.emf.ecore 2.10.2.v20150123-0348 to package javax.crypto 0.0.0.; Unable to satisfy dependency from org.eclipse.emf.ecore 2.10.2.v20150123-0348 to package javax.crypto.spec 0.0.0.; Unable to satisfy dependency from org.eclipse.equinox.p2.repository 2.3.0.v20131211-1531 to package javax.crypto 0.0.0.; Unable to satisfy dependency from org.eclipse.equinox.security 1.2.0.v20130424-1801 to package javax.crypto 0.0.0.; Unable to satisfy dependency from org.eclipse.equinox.security 1.2.0.v
20130424-1801 to package javax.crypto.spec 0.0.0.; Unable to satisfy dependency from org.eclipse.equinox.security 1.2.0.v20130424-1801 to package javax.security.auth 0.0.0.; Unable to satisfy dependency from org.eclipse.equinox.security 1.2.0.v20130424-1801 to package javax.security.auth.callback 0.0.0.; Unable to satisfy dependency from org.eclipse.equinox.security 1.2.0.v20130424-1801 to package javax.security.auth.login 0.0.0.; Unable to satisfy dependency from org.eclipse.equinox.security 1.2.0.v20130424-1801 to package javax.security.auth.spi 0.0.0.; Unable to satisfy dependency from org.eclipse.equinox.security.ui 1.1.200.v20130626-2037 to package javax.crypto.spec 0.0.0.; Unable to satisfy dependency from org.eclipse.jdt.core 3.10.0.v_OTDT_r230_201406101339 to org.eclipse.objectteam
s.otdt.core.patch.feature.group [2.0.0,3.0.0).; Unable to satisfy dependency from org.eclipse.jetty.io 8.1.14.v20131031 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from org.eclipse.jetty.io 8.1.16.v20140903 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from org.eclipse.jetty.security 8.1.14.v20131031 to package javax.security.auth 0.0.0.; Unable to satisfy dependency from org.eclipse.jetty.security 8.1.14.v20131031 to package javax.security.cert 0.0.0.; Unable to satisfy dependency from org.eclipse.jetty.security 8.1.14.v20131031 to package org.ietf.jgss 0.0.0.; Unable to satisfy dependency from org.eclipse.jetty.security 8.1.16.v20140903 to package javax.security.auth 0.0.0.; Unable to satisfy dependency from org.eclipse.jetty.security 8.1.16.v20140903 to
 package javax.security.cert 0.0.0.; Unable to satisfy dependency from org.eclipse.jetty.security 8.1.16.v20140903 to package org.ietf.jgss 0.0.0.; Unable to satisfy dependency from org.eclipse.jetty.server 8.1.14.v20131031 to package javax.naming 0.0.0.; Unable to satisfy dependency from org.eclipse.jetty.server 8.1.14.v20131031 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from org.eclipse.jetty.server 8.1.14.v20131031 to package javax.security.auth 0.0.0.; Unable to satisfy dependency from org.eclipse.jetty.server 8.1.14.v20131031 to package javax.security.cert 0.0.0.; Unable to satisfy dependency from org.eclipse.jetty.server 8.1.14.v20131031 to package javax.sql 0.0.0.; Unable to satisfy dependency from org.eclipse.jetty.server 8.1.16.v20140903 to package javax.naming
0.0.0.; Unable to satisfy dependency from org.eclipse.jetty.server 8.1.16.v20140903 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from org.eclipse.jetty.server 8.1.16.v20140903 to package javax.security.auth 0.0.0.; Unable to satisfy dependency from org.eclipse.jetty.server 8.1.16.v20140903 to package javax.security.cert 0.0.0.; Unable to satisfy dependency from org.eclipse.jetty.server 8.1.16.v20140903 to package javax.sql 0.0.0.; Unable to satisfy dependency from org.eclipse.jetty.util 8.1.14.v20131031 to package javax.imageio 0.0.0.; Unable to satisfy dependency from org.eclipse.jetty.util 8.1.14.v20131031 to package javax.net.ssl 0.0.0.; Unable to satisfy dependency from org.eclipse.jetty.util 8.1.16.v20140903 to package javax.imageio 0.0.0.; Unable to satisfy dependenc
y from org.eclipse.jetty.util 8.1.16.v20140903 to package javax.net.ssl 0.0.0.; No solution found because the problem is unsatisfiable.] -> [Help 1]

**Comment by hristostanchev** [comment]
We will recheck with Ivo once again if possible to configure Taico so only part of bundles in the project to be compiled against OSGi Minimal 1.2.

**Comment by hristostanchev** [comment]
We agree that this issue can be closed. JSE 1.7 will stay as EE in ESH bundles. Internal ProSyst build that will be setup will check if there is problem against OSGi Minimal 1.2.
