### ISSUE TITLE
Add rule events

### ISSUE THREAD

**Issue by kaikreuzer** [marinmitev/smarthome#33]
Events are currently completely missing.
Similar to the Thing infrastructure, we should have events for Rules like at least RULE_ADDED, RULE_UPDATED, RULE_REMOVED, RULE_STATUS_INFO.

**Comment by dnobel** [comment]
Will be implemented by DTAG

**Comment by danchom** [comment]
First we have to have discussion about supported events.

**Comment by dnobel** [comment]
Agree, was more a reminder for me. Just did the handover with Kai.

**Comment by JochenHiller** [comment]
Shall we consider also to fire events for RULE_ENABLED and RULE_DISABLED?

**Comment by kaikreuzer** [comment]
+1

**Comment by danchom** [comment]
RULE ENABLED and RULE DISABLED events are part of the  RULE_STATUS_INFO change event.

**Comment by kaikreuzer** [comment]
> RULE ENABLED and RULE DISABLED events are part of the RULE_STATUS_INFO change event.

Not always. If a rule is NOT_INITIALIZED, it will stay in this status (and thus there won't be a RULE_STATUS_INFO event) when a rule is switched from/to enabled/disabled. A separate event imho makes sense.

**Comment by danchom** [comment]
I'm not sure about that. If the rule is in NOT_INITIALIZED state and the rule is disabled it goes to the RULE DISABLED state and there is an state change event for that. The rule can't be not initialized and disable at the same time. The statuses of the rule are self excluding and if  a rule is not initialized it is always enabled.

**Comment by kaikreuzer** [comment]
> If the rule is in NOT_INITIALIZED state and the rule is disabled it goes to the RULE DISABLED

I do not agree. Even if a rule is disabled, it should be tried to initialize it. It should only be in state DISABLED if otherwise it would be ENABLED (or RUNNING). It is very annoying to think that a disabled rule is ready to use and just to find out when enabling it that it is e.g. lacking correct configuration - thus NOT_INITIALIZED should have precedence over the DISABLED state.

**Comment by danchom** [comment]
We already have discussed to have following self excluded rule states: disabled, not initialized, idle and running. The rule engine is implemented in that way at the moment. I didn't say that the enable rule is ready to use I said  exactly the opposite. When the rule is enabled it first has to be initialized again and if it is OK then can go to the IDLE state. The rule can be IDLE when it is disabled, but when it goes back to enabled state some of the module handlers can disappear and the rule must go into not initialized state instead of IDLE state. For that reason the not initialized can't precede the disabled state. Also I think it is an overhead to  initialize rules when they are disabled and not executed.

**Comment by dnobel** [comment]
Reading this discussion I think rule enabled/disabled is something completely different than the rule status. The rule status really says what is the technically status of a rule, that is maintained by the rule engine: e.g. if it is properly initialized or if it is running at the moment. It don´t have to be persisted and it is nothing the user wants to change. Rule enabled/disabled is a USER persistent configuration. 

So from my perspective the UI should always get the information, if it is enabled or disabled independent of the current status. The user should always has the chance to enable and disable it. So why not splitting up rule status and enabled/disabled information?

> Even if a rule is disabled, it should be tried to initialize it. It should only be in state DISABLED if otherwise it would be ENABLED (or RUNNING). It is very annoying to think that a disabled rule is ready to use and just to find out when enabling it that it is e.g. lacking correct configuration - thus NOT_INITIALIZED should have precedence over the DISABLED state.

I think if a rule is disabled, it should always be in the status uninitialized. Because it makes no sense to initialize and inform the handlers, if the rule should not be executed. Otherwise the trigger module handler itself needs to check if the rule is enabled, so that it does not trigger. But if a rule is enabled it can be either initialized or uninitialized.

Isn´t the main reason that a rule can not be initialized a missing ModuleHandlerFactory? If configuration is wrong should be checked mainly on UI side.

**Comment by dnobel** [comment]
As it has been a rule property earlier, can someone explain to me, why we removed from the rule and put it as part of the rule status?

**Comment by kaikreuzer** [comment]
> Reading this discussion I think rule enabled/disabled is something completely different than the rule status.

Correct, that's why we also designed this to be different things. The enabled/disabled information is set by the user/application, stored by the RuleRegistry and persisted. It is only one piece of information that influences the rule status.

> So from my perspective the UI should always get the information, if it is enabled or disabled independent of the current status.

I agree, it is a crucial information for the UI and thus dedicated events make sense (and not having to derive the enabled/disabled setting through the status).

> As it has been a rule property earlier, can someone explain to me, why we removed from the rule and put it as part of the rule status?

It has been removed from the rule, because we didn't want to have to persist a full rule DTO, just because one wants to change the enablement. Furthermore, the persistence must NOT be done by the ManagedRuleProvider but by the RuleRegistry, so that it is possible to enable/disable rules from other (read-only) providers as well.
We did NOT put it as part of the rule status. It is really managed separately by the RuleRegistry and there are isEnabled() and setEnabled() methods available that work independently of the rule status (which is btw transient, i.e. is not persisted).

**Comment by dnobel** [comment]
> Correct, that's why we also designed this to be different things.

If rule DISABLED is a status, I can not see that these are different things.

> I agree, it is a crucial information for the UI and thus dedicated events make sense (and not having to derive the enabled/disabled setting through the status).

The problem is, that the rule does not contain the information, if it is enabled or disabled. So if I get all rules via the REST API, I have no idea if there are enabled or not. So we do not only need events, we also need static information.

> It has been removed from the rule, because we didn't want to have to persist a full rule DTO, just because one wants to change the enablement.

But is there a problem with that? Just for performance reasons? If we want to change a tag, we also need to persist the whole rule, same for the label.

> We did NOT put it as part of the rule status. It is really managed separately by the RuleRegistry and there are isEnabled() and setEnabled() methods available that work independently of the rule status (which is btw transient, i.e. is not persisted).

Maybe than it is not implemented correctly. Because I don´t see a isEnabled() method. But should be easy to add it to the RuleRegistry. However I still think it should be part of the rule. I don´t want to make an additional REST call, just to know if the rule is enabled or disabled. Why not add it as a transient attribute to the rule? Another problem is, that also the rule status is not part of the Rule (DTO) at the moment.

**Comment by danchom** [comment]
We have removed enabled state from the Rule because:
1) Enable/disable state is not part of the rule definition. When you create a new rule you should not define its enable state. The enable state is runtime state instead of static information.
2) We can have other rule providers which are not managed providers. For these rules we have to  set enable/disabled state too.

**Comment by kaikreuzer** [comment]
> So if I get all rules via the REST API, I have no idea if there are enabled or not.

No, it is just the same way as for things. They also do NOT include their status. Only the EnrichedThingDTO includes it - and hence we will have an EnrichedRuleDTO for the REST API as well.

> Why not add it as a transient attribute to the rule?

That should imho be feasible. But is should really only be a getter method, setting the enablement has to be done through the registry.

**Comment by hristostanchev** [comment]
We agree that this issue can be closed. The REST interface will provide also status info as part of Rule info.
