### ISSUE TITLE
Add junit tests for most important classes/functionality

### ISSUE THREAD

**Issue by kaikreuzer** [marinmitev/smarthome#35]
Pure junit tests should be added for implementation classes to get some decent code coverage.

**Comment by marinmitev** [comment]
I've spent some time to get reports of the test coverage and it turned out it is not supported out of the box because test modules are separated from the source modules they test and the goal jacoco:report will generate report only for the sources of the test module itself. There should be a script that copies the jacoco.exec file to the source module and run again the jacoco:report.
There seems to be another solution which uses org.jacoco.ant plugin and is described with details here:
https://dzone.com/articles/source-control-branching-for-success
