### ISSUE TITLE
Setup automatic build

### ISSUE THREAD

**Issue by dnobel** [marinmitev/smarthome#66]
Setup an automatic build

**Comment by marinmitev** [comment]
Travis CI is ignoring MAVEN_OPTS variable
- solution with using :script definition instead of :java
  http://stackoverflow.com/questions/29201549/travis-ci-ignoring-maven-opts/29397528#29397528
- solution with specifying memory options in pom.xml files
  http://stackoverflow.com/questions/23322984/how-to-fix-maven-permgen-out-of-memory-error-on-travis-ci/25729572#25729572

**Comment by dnobel** [comment]
Solved for the moment.
